### ISSUE TITLE
Aplicación webview para android

### ISSUE THREAD

**Issue by ghost** [e-ugr/e-ugr.github.io#11]
El source está sacado de un repo de por ahí (está en el readme). El único fallo que he encontrado es que al darle al botón de telegram da un error y hay que reiniciar la app.
Se deberia de discutir el tema del logo, el gato lo he cogido de una pagina de iconos libres <https://image.freepik.com/free-icon/cat-in-black-silhouette_318-45911.jpg> pero se puede cambiar sin problemas.

<https://drive.google.com/open?id=0B0jhEiWRGDPORHAwZXAwTnpDRUE>

**Comment by canalugatete** [comment]
Hola, muchas gracias por colaborar!

El [repositorio que referencias](https://github.com/TasfiqulGhani/UltimateWebviewApplication) no indica una licencia de software libre, así que desgraciadamente no podemos usar ese código/app tal cual nos lo proporcionas 😕 

En principio podemos seguir usando la webapp, ya que convertirla en app "de verdad" no añade mucha funcionalidad. Si tuviésemos en mente crear una app, probablemente buscaríamos que tuviese más utilidad que unos cuantos accesos directos.

Gracias de nuevo, y sentimos no haber podido aprovechar tu aportación.

Saludos!
