### ISSUE TITLE
Correo UGR - Modificación

### ISSUE THREAD

**Issue by MiguelLentisco** [e-ugr/e-ugr.github.io#17]
Quería  discutir si poner directamente el enlace para estudiantes, o partir el botón que tenemos en uno para estudiantes y otro para PDI/PAS. Poner directamente el enlace sería mas cómodo en mi opinión.

**Comment by canalugatete** [comment]
Supongo que, como en principio #eugr está enfocada principalmente a estudiantes, no habría problema en simplemente dejar el enlace del webmail para estudiantes.

Cualquier otra opinión es bienvenida :3

**Comment by canalugatete** [comment]
Arreglado en #24
