### ISSUE TITLE
Cambiar background

### ISSUE THREAD

**Issue by MiguelLentisco** [e-ugr/e-ugr.github.io#23]
Buenas, a mi gusto el fondo que hay para el menú choca bastante con los botones, sobretodo con el de acceso identificado; creo que estaría bien cambiarlo por otra imagen.

**Comment by mroman42** [comment]
Es #20, una pull request de hace unos días, y entiendo de ahí que era para Halloween; a lo mejor se puede dejar unos días y cambiarlo luego (?) (cc @canalugatete)

**Comment by canalugatete** [comment]
Sí, es sólo un fondo temático para Halloween.

Estaba pensando que si la gente aporta sus fotos de edificios de la ugr se podrían ir variando un poco (y/o darle la elección al usuario), en lugar de volver simplemente al original.

**Comment by MiguelLentisco** [comment]
Cualquier fondo me parece bien siempre y cuando no quite visibilidad, el original encajaba bastante
