### ISSUE TITLE
Acceso directo al correo institucional

### ISSUE THREAD

**Issue by canalugatete** [e-ugr/e-ugr.github.io#8]

**Comment by raulng9** [comment]
Hola, ya que está en la etiqueta de hacktoberfest habrá que ayudar. ¿Dónde queréis el enlace, en index o en about? ¿Alguna otra preferencia en cuanto a estilos del link?
Un saludo.

**Comment by mroman42** [comment]
Quizá podría ser buena idea añadirlo como un botón de la misma forma que se añadió en #3 el "addon" del menú para llevar de comedores. Podría dejarse el correo institucional en el último botón (el que ahora pone Telegram), y dejar el Telegram del grupo de contracampaña de la aplicación del Santander a la derecha.

Es sugerencia de todas formas, a lo mejor @canalugatete tiene alguna idea más precisa.

**Comment by canalugatete** [comment]
Hola!

Efectivamente, lo ideal sería un botón en `index` del estilo de los que hay. Añadirlo como "addon" de otro sería útil para no romper mucho la organización actual. Tal vez a la derecha de Acceso Identificado, o como dice @M42 en lugar del telegram, dejando telegram a la derecha.

De todas formas, propón lo que creas que quede bien y ya le haremos ajustes si es necesario.

Saludos! 😸

**Comment by alexfuser** [comment]
Hola

Podría tomar este issue para realizarlo? creo que ya se como necesitan lo que requieren y lo haré hoy, lo haré como lo entendí y vean si es lo que necesita. 

Saludos.

**Comment by alexfuser** [comment]
Listo [Aqui](https://github.com/e-ugr/e-ugr.github.io/pull/15) esta el PR de la solución.

**Comment by canalugatete** [comment]
Solucionado en #15
